Always use lower case in email field
getgrav/grav-plugin-form pull request #477
Opened 2021-01-11 17:02 UTC by NicoHood

Always parse email field in lower case to avoid duplicated emails with mixed case in further processing. For example someone could subscribe for a newsletter, add a comment or rating using the same email multiple times:
* test@test.com
* TEST@test.com
* TEst@test.com

I've fixed the issue in the post processing (important), but also in the twig template. For example when someone enters an upper case default value or the string is processed via twig (in case my other PR gets merged).

2021-01-15 11:30 UTC, mahagr requested changes
I'm sorry, but I disagree with the lowercase. Presentation and logic should be separated.

2021-01-15 11:30 UTC, mahagr commented on classes/Form.php
> +                if ($field['type'] === 'email' && isset($data[$name])) {
I disagree with this. Emails should be written as they were. The logic that handles the rest should be case insensitive instead.

This is same as usernames -- in flex I allow usernames to contain mixed case, they are just normalized in the index.

Also this code is in wrong place -- post() will not be called for every form.

2021-01-15 11:30 UTC, mahagr commented on templates/forms/fields/email/email.html.twig
> +    {% set input_value = value is iterable ? value|join(',') : value|string %}
I don't think that validation supports multiple emails.

2021-01-15 11:30 UTC, mahagr commented on templates/forms/fields/email/email.html.twig
> +      value="{{ input_value|lower|e }}"
Again, IMHO values should not be lowered here.

2021-01-15 11:30 UTC, mahagr commented on templates/forms/fields/email/email.html.twig
> +    {% if inline_errors and errors %}
We need a block for this one...

2021-01-15 17:51 UTC, NicoHood commented
So I guess I can close the PR then? Or do you see any place where it would make sense to lower then email case? I've fixed my application already.

2021-01-18 09:41 UTC, mahagr commented
Multi-email is a real problem (though I do not know whether it is something we need to be concerned about.

But yes, I think lowercasing really belongs to the application logic. However, there could be a filter in the text fields to lower case / upper case text.

2021-01-18 19:03 UTC, mahagr commented
My biggest issue is that if validation changes, the form should always return the value just as it was entered by the user. I get super confused if the form alters the text I enter into it (why it failed as it looks good after filtering -- oh, it is not what I typed). 

My second issue is the separation of presentation. You have no idea how many people type their email address using capital letters in their name. But again -- emails are case insensitive, not lower case. Capital letters are not forbidden and we shouldn't enforce them to be.

2021-01-19 16:03 UTC, NicoHood commented
Alright, I will close the PR then and add a note to the docs:
https://github.com/getgrav/grav-learn/pull/896

2021-01-19 16:03 UTC, closed without merging

2021-01-20 09:09 UTC, mahagr commented
Merged docs. Thanks.