Add hCaptcha support
getgrav/grav-plugin-form pull request #562
Opened 2022-04-01 23:03 UTC by aleclerc7

This will add hCaptcha support.

- The user only needs to select the provider: reCaptcha or hCaptcha.

👉 PHP code on server side could (should) be optimized.

Tested to be working.
- reCaptcha (Google) works as before and is the default behaviour.
- hCaptcha has been tested for v2-checkbox and works.
- No error cases were tested for hCaptcha, so unknown behaviour in such cases.

Fixes #423.
Replaces #515.

Kind regards.

2022-08-25 20:47 UTC, Sailoriae commented
It would be nice if you take a look at this Pull Request, because it's a very important feature for people like me who want alternatives that are more ethical and respectful of our users than Google.

2022-10-14 20:32 UTC, robhuijben commented on blueprints.yaml
> -          help: PLUGIN_FORM.RECAPTCHA_SITE_KEY_HELP
Removing these does not seem right to me.

2022-10-14 20:36 UTC, robhuijben requested changes
Although hCaptcha is working with this drop-in replacement, there are some additions that seem to make the captcha section less understandable. For instance, hCaptcha is not using the words 'site key' and 'secret key' as a combination, but use 'site key' and 'account key'. Therefore I think it would be better to split the hCaptcha implementation from the original reCaptcha part and provide it to the end user as a standalone section in the Forms plugin configuration.

2025-01-27 13:43 UTC, erdnuesse commented
Hi, is there any major (or minor) todo on this, before it can be merged?

2025-01-27 15:50 UTC, aleclerc7 commented
I posted this code almost 3 years ago as a working drop-in replacement. I think it is still good. I have no intention to make any further changes. If someone feels things should be different, this is up to them to make changes. 😊

hCaptcha has served me well. I am now using Cloudflare (turnstile) for the same purpose (it is way better). It is available directly in the forms plugin.

Kind regards.

2025-03-26 10:23 UTC, rhukster commented
It’s not that easy. I tested this and it failed with the Ajax submission option.  That issue needs be be solved before I can merge it.

2025-03-31 23:37 UTC, rhukster commented
coming as an external plugin with next major version of the form plugin

2025-03-31 23:37 UTC, closed without merging